<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/17 07:48:57

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=internal-db.s31258.gridserver.com;dbname=db31258_emdi2013',
  'username' => 'db31258_emdi2013',
  'password' => 'hugo1712',
  'name' => 'doctrine',
)),);
