<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/06/17 07:48:56
sfConfig::add(array(
  'app_sf_guard_plugin_success_signin_url' => '/portal',
  'app_sf_guard_plugin_success_signout_url' => '/pags/inicio/inicio.html',
  'app_sf_guard_plugin_remember_key_expiration_age' => 600,
  'app_sf_guard_plugin_remember_cookie_name' => 'bitcoder',
));
