<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/17 17:29:02
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'profesor',
      ),
    ),
  ),
);
