<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/07/03 19:19:57
sfConfig::add(array(
  'mod_asignarmaterias_enabled' => true,
  'mod_asignarmaterias_view_class' => 'sfPHP',
));
