<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/06/20 14:09:54
sfConfig::add(array(
  'mod_adminestudiantes_enabled' => true,
  'mod_adminestudiantes_view_class' => 'sfPHP',
));
