<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/06/18 07:18:18
sfConfig::add(array(
  'mod_calificaciones_cdi_enabled' => true,
  'mod_calificaciones_cdi_view_class' => 'sfPHP',
));
