<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/06/17 11:19:51
sfConfig::add(array(
  'mod_calificaciones_enabled' => true,
  'mod_calificaciones_view_class' => 'sfPHP',
));
