<?php

/**
 * emdiGrado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    emdi
 * @subpackage model
 * @author     Bitcoder
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class emdiGrado extends BaseemdiGrado
{
    public function __toString()
    {
    return $this->getGraNombre();
    }
}