<?php

/**
 * emdiAdministracionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiAdministracionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiAdministracionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiAdministracion');
    }
}