<?php

/**
 * emdiComRepresentanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiComRepresentanteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiComRepresentanteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiComRepresentante');
    }
}