<?php

/**
 * emdiComXGradoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiComXGradoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiComXGradoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiComXGrado');
    }
}