<?php

/**
 * emdiPlantillaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiPlantillaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiPlantillaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiPlantilla');
    }
}