<?php

/**
 * emdiMateriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiMateriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiMateriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiMateria');
    }
}