<?php

/**
 * emdiEstudiante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    emdi
 * @subpackage model
 * @author     Bitcoder
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class emdiEstudiante extends BaseemdiEstudiante
{
    public function __toString()
    {
        return $this->getEstNombres()." ".$this->getEstApellidos();
    }
    
    public function getNotaEstudiante($materiaId, $codParcial) {
        $nota = '';
        
        $nota = Doctrine::getTable('emdiNota')
                    ->createQuery('n')
                    ->where('n.est_id = ? AND n.mat_id = ? AND n.not_codigo_parcial = ?', 
                                array($this->getEstId(), $materiaId, $codParcial))
                    ->execute();
        
        return $nota;
    }
    
    public function getNotasMateria($materiaId) {
        $notas = array();
        
        $consulta = Doctrine::getTable('emdiNota')
                    ->createQuery('n')
                    ->where('n.est_id = ? AND n.mat_id = ?', 
                                array($this->getEstId(), $materiaId))
                    ->fetchArray();
        
        foreach ($consulta AS $nota) {
            
            $notas[$nota['not_codigo_parcial']] = $nota['not_nota'];
        }

//        echo "<br />";
//        echo "<br />";
//        echo "<br />";
//         echo "<pre>";
//        print_r($notas);
//////        print_r($sf_data->getRaw('notas_estudiante'));
////        echo array_key_exists(1, $notas_estudiante);
////        
//         echo "</pre>";
//        echo "<br />";
//        echo "<br />";
//        echo "<br />";
//        
        return $notas;
    }
}