<?php

/**
 * emdiGradoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiGradoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiGradoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiGrado');
    }
}