<?php

/**
 * emdiComGeneralTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiComGeneralTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiComGeneralTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiComGeneral');
    }
}