<?php

/**
 * emdiProfesorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiProfesorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiProfesorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiProfesor');
    }
}