<?php

/**
 * emdiAgendaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiAgendaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiAgendaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiAgenda');
    }
}