<?php

/**
 * emdiTareaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiTareaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiTareaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiTarea');
    }
}