<?php

/**
 * emdiComProfesor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    emdi
 * @subpackage model
 * @author     Bitcoder
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class emdiComProfesor extends BaseemdiComProfesor
{
  
  /**
   * Funcion para ingresar un comunicado via AJAX
   * @param unknown $entrada
   * @return multitype:string
   */
  public static function ingresarComunicado($entrada){

    if(isset ($entrada['cpr_referencia'])) {
      $cpr_referencia = $entrada['cpr_referencia'];
    } else {
      $error = "No se ha definido un grado/materia";
      return array('tipo' => 'error', 'mensaje' => $error);
    }
     
    if(isset ($entrada['est_id'])) {
      $est_id = $entrada['est_id'];
    } else {
      $error = "No se ha definido un estudiante";
      return array('tipo' => 'error', 'mensaje' => $error);
    }
    
    
    if(isset ($entrada['cpr_contenido'])) {
      $cpr_contenido = $entrada['cpr_contenido'];
    } else {
      $error =  "No se ha definido un contenido";
      return array('tipo' => 'error', 'mensaje' => $error);
    }
    
    if(isset ($entrada['pro_id'])) {
      $pro_id = $entrada['pro_id'];
    } else {
      $error =  "No se ha definido un profesor";
      return array('tipo' => 'error', 'mensaje' => $error);
    }

    $comunicado = new emdiComProfesor();
    $comunicado->setCprReferencia($cpr_referencia);
    $comunicado->setCprContenido($cpr_contenido);
    $comunicado->setEstId($est_id);
    $comunicado->setProId($pro_id);

    $comunicado->save();
    
    return array('tipo' => 'notice', 'mensaje' => 'El comunicado fue enviado exitosamente.');
  }

}