<?php

/**
 * emdiComGeneral
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    emdi
 * @subpackage model
 * @author     Bitcoder
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class emdiComGeneral extends BaseemdiComGeneral
{
  
  

  /**
   * BaseemdiComGeneral
   *
   * This class has been auto-generated by the Doctrine ORM Framework
   *
   * @property integer $cge_id
   * @property clob $cge_contenido
   * @property string $cge_referencia
   * @property Doctrine_Collection $emdi_com_x_gradoes
   *
   * @method integer             getCgeId()              Returns the current record's "cge_id" value
   * @method clob                getCgeContenido()       Returns the current record's "cge_contenido" value
   * @method string              getCgeReferencia()      Returns the current record's "cge_referencia" value
   * @method Doctrine_Collection getEmdiComXGradoes()    Returns the current record's "emdi_com_x_gradoes" collection
   * @method emdiComGeneral      setCgeId()              Sets the current record's "cge_id" value
   * @method emdiComGeneral      setCgeContenido()       Sets the current record's "cge_contenido" value
   * @method emdiComGeneral      setCgeReferencia()      Sets the current record's "cge_referencia" value
   * @method emdiComGeneral      setEmdiComXGradoes()    Sets the current record's "emdi_com_x_gradoes" collection
   *
   * @package    emdi
   * @subpackage model
   * @author     Bitcoder
   * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
   */
  
  
  
  /**
   * Funcion para ingresar un comunicado via AJAX
   * @param unknown $entrada
   * @return multitype:string
   */
  public static function ingresarComunicado($entrada){
  
    if(isset ($entrada['cge_referencia'])) {
      $cpr_referencia = $entrada['cge_referencia'];
    } else {
      $error = "No se ha definido una referencia";
      return array('tipo' => 'error', 'mensaje' => $error);
    }
  
    if(isset ($entrada['cge_contenido'])) {
      $cge_contenido = $entrada['cge_contenido'];
    } else {
      $error =  "No se ha definido un contenido";
      return array('tipo' => 'error', 'mensaje' => $error);
    }
  
    // Guardo el comunicado
    $comunicado = new emdiComGeneral();
    $comunicado['cge_referencia'] = $cpr_referencia;
    $comunicado['cge_contenido'] = $cge_contenido;
    $comunicado->save();
    
    // Asocio el comunicado a cada grado seleccionado
    foreach ($entrada['grados_id'] as $grado){
      
      $com_grado = new emdiComXGrado();
      $com_grado['gra_id'] = $grado;
      $com_grado['cge_id'] = $comunicado['cge_id'];
      $com_grado->save();
    }
  
    return array('tipo' => 'notice', 'mensaje' => 'El comunicado fue enviado exitosamente.');
  }
  
}