<?php

/**
 * emdiAdjuntoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiAdjuntoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiAdjuntoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiAdjunto');
    }
}