<?php

/**
 * emdiMateriaXGradoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiMateriaXGradoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiMateriaXGradoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiMateriaXGrado');
    }
}