<?php

/**
 * emdiEstudianteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiEstudianteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiEstudianteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiEstudiante');
    }
}