<?php

/**
 * emdiComIndividualTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiComIndividualTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiComIndividualTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiComIndividual');
    }
}