<?php

/**
 * emdiComProfesorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emdiComProfesorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emdiComProfesorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emdiComProfesor');
    }
}