<?php

/**
 * BaseemdiComGeneral
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cge_id
 * @property clob $cge_contenido
 * @property string $cge_referencia
 * @property Doctrine_Collection $emdi_com_x_gradoes
 * 
 * @method integer             getCgeId()              Returns the current record's "cge_id" value
 * @method clob                getCgeContenido()       Returns the current record's "cge_contenido" value
 * @method string              getCgeReferencia()      Returns the current record's "cge_referencia" value
 * @method Doctrine_Collection getEmdiComXGradoes()    Returns the current record's "emdi_com_x_gradoes" collection
 * @method emdiComGeneral      setCgeId()              Sets the current record's "cge_id" value
 * @method emdiComGeneral      setCgeContenido()       Sets the current record's "cge_contenido" value
 * @method emdiComGeneral      setCgeReferencia()      Sets the current record's "cge_referencia" value
 * @method emdiComGeneral      setEmdiComXGradoes()    Sets the current record's "emdi_com_x_gradoes" collection
 * 
 * @package    emdi
 * @subpackage model
 * @author     Bitcoder
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseemdiComGeneral extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emdi_com_general');
        $this->hasColumn('cge_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cge_contenido', 'clob', 65535, array(
             'type' => 'clob',
             'notnull' => true,
             'length' => 65535,
             ));
        $this->hasColumn('cge_referencia', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));

        $this->option('collate', 'utf8_spanish_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('emdiComXGrado as emdi_com_x_gradoes', array(
             'local' => 'cge_id',
             'foreign' => 'cge_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}