<?php

/**
 * BaseemdiComGeneral
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cge_id
 * @property string $cge_codigo
 * @property date $cge_fecha_envio
 * @property clob $cge_contenido
 * @property string $cge_tipo
 * @property string $cge_seccion
 * @property integer $gra_id
 * @property emdiGrado $gra
 * 
 * @method integer        getCgeId()           Returns the current record's "cge_id" value
 * @method string         getCgeCodigo()       Returns the current record's "cge_codigo" value
 * @method date           getCgeFechaEnvio()   Returns the current record's "cge_fecha_envio" value
 * @method clob           getCgeContenido()    Returns the current record's "cge_contenido" value
 * @method string         getCgeTipo()         Returns the current record's "cge_tipo" value
 * @method string         getCgeSeccion()      Returns the current record's "cge_seccion" value
 * @method integer        getGraId()           Returns the current record's "gra_id" value
 * @method emdiGrado      getGra()             Returns the current record's "gra" value
 * @method emdiComGeneral setCgeId()           Sets the current record's "cge_id" value
 * @method emdiComGeneral setCgeCodigo()       Sets the current record's "cge_codigo" value
 * @method emdiComGeneral setCgeFechaEnvio()   Sets the current record's "cge_fecha_envio" value
 * @method emdiComGeneral setCgeContenido()    Sets the current record's "cge_contenido" value
 * @method emdiComGeneral setCgeTipo()         Sets the current record's "cge_tipo" value
 * @method emdiComGeneral setCgeSeccion()      Sets the current record's "cge_seccion" value
 * @method emdiComGeneral setGraId()           Sets the current record's "gra_id" value
 * @method emdiComGeneral setGra()             Sets the current record's "gra" value
 * 
 * @package    emdi
 * @subpackage model
 * @author     Bitcoder
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseemdiComGeneral extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emdi_com_general');
        $this->hasColumn('cge_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cge_codigo', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 15,
             ));
        $this->hasColumn('cge_fecha_envio', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('cge_contenido', 'clob', 65535, array(
             'type' => 'clob',
             'notnull' => true,
             'length' => 65535,
             ));
        $this->hasColumn('cge_tipo', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('cge_seccion', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('gra_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('fk_emdi_comunicado_gen_emdi_grado1_idx', array(
             'fields' => 
             array(
              0 => 'gra_id',
             ),
             ));
        $this->option('collate', 'utf8_spanish_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('emdiGrado as gra', array(
             'local' => 'gra_id',
             'foreign' => 'gra_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}