<?php

/**
 * BaseemdiComProfesor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cpr_id
 * @property string $cpr_contenido
 * @property string $cpr_referencia
 * @property integer $est_id
 * @property integer $pro_id
 * @property emdiEstudiante $est
 * @property emdiProfesor $pro
 * 
 * @method integer         getCprId()          Returns the current record's "cpr_id" value
 * @method string          getCprContenido()   Returns the current record's "cpr_contenido" value
 * @method string          getCprReferencia()  Returns the current record's "cpr_referencia" value
 * @method integer         getEstId()          Returns the current record's "est_id" value
 * @method integer         getProId()          Returns the current record's "pro_id" value
 * @method emdiEstudiante  getEst()            Returns the current record's "est" value
 * @method emdiProfesor    getPro()            Returns the current record's "pro" value
 * @method emdiComProfesor setCprId()          Sets the current record's "cpr_id" value
 * @method emdiComProfesor setCprContenido()   Sets the current record's "cpr_contenido" value
 * @method emdiComProfesor setCprReferencia()  Sets the current record's "cpr_referencia" value
 * @method emdiComProfesor setEstId()          Sets the current record's "est_id" value
 * @method emdiComProfesor setProId()          Sets the current record's "pro_id" value
 * @method emdiComProfesor setEst()            Sets the current record's "est" value
 * @method emdiComProfesor setPro()            Sets the current record's "pro" value
 * 
 * @package    emdi
 * @subpackage model
 * @author     Bitcoder
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseemdiComProfesor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emdi_com_profesor');
        $this->hasColumn('cpr_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cpr_contenido', 'string', 300, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 300,
             ));
        $this->hasColumn('cpr_referencia', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('est_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('pro_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_emdi_comunicado_ind_emdi_estudiante1_idx', array(
             'fields' => 
             array(
              0 => 'est_id',
             ),
             ));
        $this->index('fk_emdi_comunicado_ind_emdi_profesor1_idx', array(
             'fields' => 
             array(
              0 => 'pro_id',
             ),
             ));
        $this->option('collate', 'utf8_spanish_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('emdiEstudiante as est', array(
             'local' => 'est_id',
             'foreign' => 'est_id'));

        $this->hasOne('emdiProfesor as pro', array(
             'local' => 'pro_id',
             'foreign' => 'pro_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}