<?php

/**
 * BaseemdiAdministracion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $adm_id
 * @property boolean $adm_habilitar_nota1
 * @property boolean $adm_habilitar_nota2
 * @property boolean $adm_habilitar_nota3
 * @property boolean $adm_habilitar_nota4
 * @property boolean $adm_habilitar_nota5
 * @property boolean $adm_habilitar_nota6
 * @property boolean $adm_habilitar_nota7
 * @property boolean $adm_habilitar_nota8
 * @property boolean $adm_habilitar_nota9
 * @property boolean $adm_habilitar_nota10
 * @property boolean $adm_habilitar_nota11
 * @property boolean $adm_habilitar_nota12
 * 
 * @method integer            getAdmId()                Returns the current record's "adm_id" value
 * @method boolean            getAdmHabilitarNota1()    Returns the current record's "adm_habilitar_nota1" value
 * @method boolean            getAdmHabilitarNota2()    Returns the current record's "adm_habilitar_nota2" value
 * @method boolean            getAdmHabilitarNota3()    Returns the current record's "adm_habilitar_nota3" value
 * @method boolean            getAdmHabilitarNota4()    Returns the current record's "adm_habilitar_nota4" value
 * @method boolean            getAdmHabilitarNota5()    Returns the current record's "adm_habilitar_nota5" value
 * @method boolean            getAdmHabilitarNota6()    Returns the current record's "adm_habilitar_nota6" value
 * @method boolean            getAdmHabilitarNota7()    Returns the current record's "adm_habilitar_nota7" value
 * @method boolean            getAdmHabilitarNota8()    Returns the current record's "adm_habilitar_nota8" value
 * @method boolean            getAdmHabilitarNota9()    Returns the current record's "adm_habilitar_nota9" value
 * @method boolean            getAdmHabilitarNota10()   Returns the current record's "adm_habilitar_nota10" value
 * @method boolean            getAdmHabilitarNota11()   Returns the current record's "adm_habilitar_nota11" value
 * @method boolean            getAdmHabilitarNota12()   Returns the current record's "adm_habilitar_nota12" value
 * @method emdiAdministracion setAdmId()                Sets the current record's "adm_id" value
 * @method emdiAdministracion setAdmHabilitarNota1()    Sets the current record's "adm_habilitar_nota1" value
 * @method emdiAdministracion setAdmHabilitarNota2()    Sets the current record's "adm_habilitar_nota2" value
 * @method emdiAdministracion setAdmHabilitarNota3()    Sets the current record's "adm_habilitar_nota3" value
 * @method emdiAdministracion setAdmHabilitarNota4()    Sets the current record's "adm_habilitar_nota4" value
 * @method emdiAdministracion setAdmHabilitarNota5()    Sets the current record's "adm_habilitar_nota5" value
 * @method emdiAdministracion setAdmHabilitarNota6()    Sets the current record's "adm_habilitar_nota6" value
 * @method emdiAdministracion setAdmHabilitarNota7()    Sets the current record's "adm_habilitar_nota7" value
 * @method emdiAdministracion setAdmHabilitarNota8()    Sets the current record's "adm_habilitar_nota8" value
 * @method emdiAdministracion setAdmHabilitarNota9()    Sets the current record's "adm_habilitar_nota9" value
 * @method emdiAdministracion setAdmHabilitarNota10()   Sets the current record's "adm_habilitar_nota10" value
 * @method emdiAdministracion setAdmHabilitarNota11()   Sets the current record's "adm_habilitar_nota11" value
 * @method emdiAdministracion setAdmHabilitarNota12()   Sets the current record's "adm_habilitar_nota12" value
 * 
 * @package    emdi
 * @subpackage model
 * @author     Bitcoder
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseemdiAdministracion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emdi_administracion');
        $this->hasColumn('adm_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unique' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('adm_habilitar_nota1', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('adm_habilitar_nota2', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('adm_habilitar_nota3', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('adm_habilitar_nota4', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('adm_habilitar_nota5', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('adm_habilitar_nota6', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('adm_habilitar_nota7', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('adm_habilitar_nota8', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('adm_habilitar_nota9', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('adm_habilitar_nota10', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('adm_habilitar_nota11', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('adm_habilitar_nota12', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_spanish_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}