<?php

/**
 * BaseemdiAgenda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $age_id
 * @property string $age_firma
 * @property integer $est_id
 * @property emdiEstudiante $est
 * 
 * @method integer        getAgeId()     Returns the current record's "age_id" value
 * @method string         getAgeFirma()  Returns the current record's "age_firma" value
 * @method integer        getEstId()     Returns the current record's "est_id" value
 * @method emdiEstudiante getEst()       Returns the current record's "est" value
 * @method emdiAgenda     setAgeId()     Sets the current record's "age_id" value
 * @method emdiAgenda     setAgeFirma()  Sets the current record's "age_firma" value
 * @method emdiAgenda     setEstId()     Sets the current record's "est_id" value
 * @method emdiAgenda     setEst()       Sets the current record's "est" value
 * 
 * @package    emdi
 * @subpackage model
 * @author     Bitcoder
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseemdiAgenda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emdi_agenda');
        $this->hasColumn('age_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('age_firma', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'fixed' => 1,
             'length' => 1,
             ));
        $this->hasColumn('est_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_emdi_agenda_emdi_estudiante1_idx', array(
             'fields' => 
             array(
              0 => 'est_id',
             ),
             ));
        $this->option('collate', 'utf8_spanish_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('emdiEstudiante as est', array(
             'local' => 'est_id',
             'foreign' => 'est_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}