<?php

/**
 * BaseemdiComXGrado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cxg
 * @property integer $cge_id
 * @property integer $gra_id
 * @property emdiComGeneral $cge
 * @property emdiGrado $gra
 * 
 * @method integer        getCxg()    Returns the current record's "cxg" value
 * @method integer        getCgeId()  Returns the current record's "cge_id" value
 * @method integer        getGraId()  Returns the current record's "gra_id" value
 * @method emdiComGeneral getCge()    Returns the current record's "cge" value
 * @method emdiGrado      getGra()    Returns the current record's "gra" value
 * @method emdiComXGrado  setCxg()    Sets the current record's "cxg" value
 * @method emdiComXGrado  setCgeId()  Sets the current record's "cge_id" value
 * @method emdiComXGrado  setGraId()  Sets the current record's "gra_id" value
 * @method emdiComXGrado  setCge()    Sets the current record's "cge" value
 * @method emdiComXGrado  setGra()    Sets the current record's "gra" value
 * 
 * @package    emdi
 * @subpackage model
 * @author     Bitcoder
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseemdiComXGrado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emdi_com_x_grado');
        $this->hasColumn('cxg', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cge_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('gra_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_emdi_com_x_grado_emdi_com_general1_idx', array(
             'fields' => 
             array(
              0 => 'cge_id',
             ),
             ));
        $this->index('fk_emdi_com_x_grado_emdi_grado1_idx', array(
             'fields' => 
             array(
              0 => 'gra_id',
             ),
             ));
        $this->option('collate', 'utf8_spanish_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('emdiComGeneral as cge', array(
             'local' => 'cge_id',
             'foreign' => 'cge_id'));

        $this->hasOne('emdiGrado as gra', array(
             'local' => 'gra_id',
             'foreign' => 'gra_id'));
    }
}