<?php

/**
 * BaseemdiTarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tar_id
 * @property date $tar_fecha_envio
 * @property date $tar_fecha_entrega
 * @property string $tar_contenido
 * @property integer $mxg_id
 * @property emdiMateriaXGrado $mxg
 * @property Doctrine_Collection $emdi_adjuntos
 * 
 * @method integer             getTarId()             Returns the current record's "tar_id" value
 * @method date                getTarFechaEnvio()     Returns the current record's "tar_fecha_envio" value
 * @method date                getTarFechaEntrega()   Returns the current record's "tar_fecha_entrega" value
 * @method string              getTarContenido()      Returns the current record's "tar_contenido" value
 * @method integer             getMxgId()             Returns the current record's "mxg_id" value
 * @method emdiMateriaXGrado   getMxg()               Returns the current record's "mxg" value
 * @method Doctrine_Collection getEmdiAdjuntos()      Returns the current record's "emdi_adjuntos" collection
 * @method emdiTarea           setTarId()             Sets the current record's "tar_id" value
 * @method emdiTarea           setTarFechaEnvio()     Sets the current record's "tar_fecha_envio" value
 * @method emdiTarea           setTarFechaEntrega()   Sets the current record's "tar_fecha_entrega" value
 * @method emdiTarea           setTarContenido()      Sets the current record's "tar_contenido" value
 * @method emdiTarea           setMxgId()             Sets the current record's "mxg_id" value
 * @method emdiTarea           setMxg()               Sets the current record's "mxg" value
 * @method emdiTarea           setEmdiAdjuntos()      Sets the current record's "emdi_adjuntos" collection
 * 
 * @package    emdi
 * @subpackage model
 * @author     Bitcoder
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseemdiTarea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emdi_tareas');
        $this->hasColumn('tar_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unique' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tar_fecha_envio', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('tar_fecha_entrega', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('tar_contenido', 'string', 300, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 300,
             ));
        $this->hasColumn('mxg_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_emdi_tareas_emdi_materia_x_grado1_idx', array(
             'fields' => 
             array(
              0 => 'mxg_id',
             ),
             ));
        $this->option('collate', 'utf8_spanish_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('emdiMateriaXGrado as mxg', array(
             'local' => 'mxg_id',
             'foreign' => 'mxg_id'));

        $this->hasMany('emdiAdjunto as emdi_adjuntos', array(
             'local' => 'tar_id',
             'foreign' => 'tar_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}