<?php

/**
 * BaseemdiPlantilla
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pla_id
 * @property string $pla_contenido
 * 
 * @method integer       getPlaId()         Returns the current record's "pla_id" value
 * @method string        getPlaContenido()  Returns the current record's "pla_contenido" value
 * @method emdiPlantilla setPlaId()         Sets the current record's "pla_id" value
 * @method emdiPlantilla setPlaContenido()  Sets the current record's "pla_contenido" value
 * 
 * @package    emdi
 * @subpackage model
 * @author     Bitcoder
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseemdiPlantilla extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emdi_plantilla');
        $this->hasColumn('pla_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('pla_contenido', 'string', 300, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 300,
             ));

        $this->option('collate', 'utf8_spanish_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}